services:
  advanced-backend:
    build: ./backend
    ports:
      - "5000:5000"
    networks:
      - advanced-network

  advanced-frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - advanced-backend
    environment:
      - BACKEND_URL=http://advanced-backend:5000
    networks:
      - advanced-network

networks:
  advanced-network:
    driver: bridge
